// src/components/chocobun_tools/BMICalc.vue
<template>
  <v-dialog v-model="open" fullscreen hide-overlay transition="dialog-bottom-transition">
    <v-card>
      <v-toolbar dark color="primary">
        <v-toolbar-title>BMI Calculator</v-toolbar-title>
        <v-spacer></v-spacer>
        <v-toolbar-items>
          <slot name="toolbar-items"></slot>
        </v-toolbar-items>
      </v-toolbar>

      <!-- BMI Calculator -->
      <v-card tile>
        <v-tabs v-model="tab" fixed-tabs>
          <v-tab>Adult</v-tab>
          <v-tab>Child</v-tab>
        </v-tabs>

        <v-tabs-items v-model="tab">
          <!-- Adult Tab -->
          <v-tab-item>
            <v-dialog v-model="openAdultResult">
              <v-card>
                <v-card-title>Results</v-card-title>
                <v-card-text class="px-2 pb-0">
                  <v-simple-table dense>
                    <template v-slot:default>
                      <tbody>
                        <tr>
                          <td>BMI</td>
                          <td>{{adultBMI}}</td>
                        </tr>
                        <tr>
                          <td>Asia Classification</td>
                          <td>{{ adultAsia }}</td>
                        </tr>
                        <tr>
                          <td>WHO Classification</td>
                          <td>{{ adultWHO }}</td>
                        </tr>
                      </tbody>
                    </template>
                  </v-simple-table>
                </v-card-text>
                <v-card-actions>
                  <v-spacer></v-spacer>
                  <v-btn text color="secondary" @click="openAdultResult = false">Close</v-btn>
                </v-card-actions>
              </v-card>
            </v-dialog>
            <v-card flat class="pa-5">
              <v-form ref="adultForm">
                <v-radio-group v-model="adultHtUnit" dense row class="mt-0 pt-0">
                  <v-radio value="cm" label="Centimeters" />
                  <v-radio value="ft" label="Feet, inches" />
                </v-radio-group>
                <div class="height">
                  <v-text-field
                    v-model="adultHeight"
                    outlined
                    dense
                    label="Height"
                    type="number"
                    :suffix="adultHtUnit"
                    :rules="numbersOnly"
                  ></v-text-field>
                  <v-text-field
                    v-model="adultInches"
                    outlined
                    dense
                    suffix="in"
                    type="number"
                    v-if="adultHtUnit === 'ft'"
                    :rules="numbersOnly"
                  ></v-text-field>
                </div>
                <v-radio-group v-model="adultWtUnit" dense row class="mt-0 pt-0">
                  <v-radio value="kg" label="Kilograms" />
                  <v-radio value="lbs" label="Pounds" />
                </v-radio-group>
                <v-text-field
                  v-model="adultWeight"
                  outlined
                  dense
                  label="Weight"
                  type="number"
                  :suffix="adultWtUnit"
                  :rules="numbersOnly"
                ></v-text-field>
              </v-form>
              <v-card-actions class="ma-0 pa-0">
                <v-spacer></v-spacer>
                <v-btn text color="primary" @click="clearAdult">Clear</v-btn>
                <v-btn text color="primary" @click="computeAdult">Compute</v-btn>
              </v-card-actions>
            </v-card>
          </v-tab-item>

          <!-- Child Tab -->
          <v-tab-item>
            <v-dialog v-model="openChildResult">
              <v-card>
                <v-card-title>Results</v-card-title>
                <v-card-text class="px-2 pb-0">
                  <v-simple-table dense>
                    <template v-slot:default>
                      <tbody>
                        <tr>
                          <td>Age</td>
                          <td>{{ childAge }}</td>
                        </tr>
                        <tr>
                          <td>BMI</td>
                          <td>{{ childBMI }}</td>
                        </tr>
                        <tr>
                          <td>Percentile</td>
                          <td>
                            <span>{{ childPercentile.percent }}</span>
                            <sup>{{ childPercentile.suffix }}</sup>
                          </td>
                        </tr>
                        <tr>
                          <td>ZScore</td>
                          <td>{{ childZScore }}</td>
                        </tr>
                        <tr>
                          <td>Classification</td>
                          <td>{{ childClassify }}</td>
                        </tr>
                      </tbody>
                    </template>
                  </v-simple-table>
                </v-card-text>
                <v-card-actions>
                  <v-spacer></v-spacer>
                  <v-btn text color="secondary" @click="openChildResult = false">Close</v-btn>
                </v-card-actions>
              </v-card>
            </v-dialog>
            <v-card flat class="pa-5">
              <v-form ref="childForm">
                <div class="bday-and-sex">
                  <v-select v-model="childSex" :items="sex" label="Sex" dense outlined></v-select>
                  <v-dialog
                    ref="dialog"
                    v-model="datePicker"
                    :return-value.sync="childBirthday"
                    persistent
                    width="290px"
                  >
                    <template v-slot:activator="{ on }">
                      <v-text-field
                        v-model="childBirthday"
                        label="Birthday"
                        prepend-inner-icon="event"
                        readonly
                        v-on="on"
                        dense
                        outlined
                      ></v-text-field>
                    </template>
                    <v-date-picker
                      v-model="childBirthday"
                      :max="new Date(new Date().setFullYear(new Date().getFullYear() - 2)).toISOString().substr(0, 10)"
                      :min="new Date(new Date().setFullYear(new Date().getFullYear() - 20)).toISOString().substr(0, 10)"
                    >
                      <v-spacer></v-spacer>
                      <v-btn text color="secondary" @click="datePicker = false">Cancel</v-btn>
                      <v-btn text color="secondary" @click="$refs.dialog.save(childBirthday)">OK</v-btn>
                    </v-date-picker>
                  </v-dialog>
                </div>
                <v-radio-group v-model="childHtUnit" dense row class="mt-0 pt-0">
                  <v-radio value="cm" label="Centimeters" />
                  <v-radio value="ft" label="Feet, inches" />
                </v-radio-group>
                <div class="height">
                  <v-text-field
                    v-model="childHeight"
                    outlined
                    dense
                    label="Height"
                    type="number"
                    :suffix="childHtUnit"
                    :rules="numbersOnly"
                  ></v-text-field>
                  <v-text-field
                    v-model="childInches"
                    outlined
                    dense
                    suffix="in"
                    type="number"
                    v-if="childHtUnit === 'ft'"
                    :rules="numbersOnly"
                  ></v-text-field>
                </div>
                <v-radio-group v-model="childWtUnit" dense row class="mt-0 pt-0">
                  <v-radio value="kg" label="Kilograms" />
                  <v-radio value="lbs" label="Pounds" />
                </v-radio-group>
                <v-text-field
                  v-model="childWeight"
                  outlined
                  dense
                  label="Weight"
                  type="number"
                  :suffix="childWtUnit"
                  :rules="numbersOnly"
                ></v-text-field>
              </v-form>
              <v-card-actions class="ma-0 pa-0">
                <v-spacer></v-spacer>
                <v-btn text color="primary" @click="clearChild">Clear</v-btn>
                <v-btn text color="primary" @click="computeChild">Compute</v-btn>
              </v-card-actions>
            </v-card>
          </v-tab-item>
        </v-tabs-items>
      </v-card>
    </v-card>
  </v-dialog>
</template>

<script>
export default {
  props: {
    open: {
      type: Boolean,
      default: false
    }
  },
  data: () => ({
    tab: 0,
    sex: [
      { text: "Male", value: 1 },
      { text: "Female", value: 2 }
    ],
    openAdultResult: false,
    openChildResult: false,
    datePicker: false,
    adultHtUnit: "cm",
    adultWtUnit: "kg",
    adultBMI: "",
    adultAsia: "",
    adultWHO: "",
    adultHeight: "",
    adultInches: "",
    adultWeight: "",
    childHtUnit: "cm",
    childWtUnit: "kg",
    childHeight: "",
    childInches: "",
    childWeight: "",
    childSex: 1,
    childAge: "",
    childBMI: "",
    childPercentile: {},
    childZScore: "",
    childClassify: "",
    childBirthday: new Date(
      new Date().setFullYear(new Date().getFullYear() - 2)
    )
      .toISOString()
      .substr(0, 10),
    numbersOnly: [v => v && !isNaN(v)]
  }),
  methods: {
    computeBMI(wtUnit, wt, htUnit, ht, inch) {
      let m, kg;
      // Convert height to meters
      if (htUnit === "cm") {
        m = ht * 0.01;
      } else {
        m = (ht * 12 + +inch) * 0.0254;
      }
      // Convert weight to kg
      if (wtUnit === "kg") {
        kg = wt;
      } else {
        kg = wt * 0.45359237;
      }
      const bmi = (kg / m ** 2).toFixed(1);
      return bmi;
    },
    zscoreToPercentile(zscore) {
      // zscore is the number of standard deviations from the mean

      // If zscore is greater than 6.5 standard deviations from the mean,
      // The number of significant digits will be outside of a reasonable range
      if (zscore < -6.5) return 0.0;
      if (zscore > 6.5) return 1.0;

      let factK = 1;
      let sum = 0;
      let term = 1;
      let k = 0;
      const loopStop = Math.exp(-23);
      while (Math.abs(term) > loopStop) {
        term =
          (((0.3989422804 * Math.pow(-1, k) * Math.pow(zscore, k)) /
            (2 * k + 1) /
            Math.pow(2, k)) *
            Math.pow(zscore, k + 1)) /
          factK;
        sum += term;
        k++;
        factK *= k;
      }
      sum += 0.5;

      return sum;
    },
    computeAdult() {
      if (this.$refs.adultForm.validate()) {
        // Compute BMI
        this.adultBMI = this.computeBMI(
          this.adultWtUnit,
          this.adultWeight,
          this.adultHtUnit,
          this.adultHeight,
          this.adultInches
        );
        // Classify BMI
        if (this.adultBMI < 18.5) {
          this.adultAsia = "Underweight";
          this.adultWHO = "Underweight";
        } else if (this.adultBMI < 23) {
          this.adultAsia = "Normal";
          this.adultWHO = "Normal";
        } else if (this.adultBMI < 25) {
          this.adultAsia = "Overweight";
          this.adultWHO = "Normal";
        } else if (this.adultBMI < 30) {
          this.adultAsia = "Obese";
          this.adultWHO = "Overweight";
        } else if (this.adultBMI < 35) {
          this.adultAsia = "Obese";
          this.adultWHO = "Obese class I";
        } else if (this.adultBMI < 40) {
          this.adultAsia = "Obese";
          this.adultWHO = "Obese class II";
        } else {
          this.adultAsia = "Obese";
          this.adultWHO = "Obese class III";
        }
        this.openAdultResult = true;
      }
    },
    clearAdult() {
      this.$refs.adultForm.resetValidation();
      this.adultHtUnit = "cm";
      this.adultWtUnit = "kg";
      this.adultBMI = "";
      this.adultAsia = "";
      this.adultWHO = "";
      this.adultHeight = "";
      this.adultInches = "";
      this.adultWeight = "";
    },
    computeChild() {
      if (this.$refs.childForm.validate()) {
        // Compute BMI
        this.childBMI = this.computeBMI(
          this.childWtUnit,
          this.childWeight,
          this.childHtUnit,
          this.childHeight,
          this.childInches
        );

        // Determine age
        const ms = new Date() - new Date(this.childBirthday);
        const mos = Math.floor(ms / 2629746000);
        const yrs = Math.floor(mos / 12);
        let remainderMos = mos % 12;
        this.childAge = `${yrs} years & ${remainderMos} ${
          remainderMos === 1 ? "month" : "months"
        }`;

        // Calculate ZScore
        const data = require("@/assets/BMI/LMS.json");
        const lms = data.find(x => x.sex === this.childSex && x.mos === mos);
        const rawZScore =
          ((this.childBMI / lms.m) ** lms.l - 1) / (lms.l * lms.s);
        this.childZScore = rawZScore.toFixed(2);

        // Calculate Percentile
        const rawPercentile = Math.round(
          this.zscoreToPercentile(rawZScore) * 100
        );
        // Append ordinal suffix
        let ordinalSuffix;
        const digits = rawPercentile
          .toString()
          .split("")
          .reverse();
        if (digits[1] !== "1") {
          switch (digits[0]) {
            case "1":
              ordinalSuffix = "st";
              break;
            case "2":
              ordinalSuffix = "nd";
              break;
            case "3":
              ordinalSuffix = "rd";
              break;
            default:
              ordinalSuffix = "th";
          }
        } else {
          ordinalSuffix = "th";
        }
        this.childPercentile.percent = rawPercentile;
        this.childPercentile.suffix = ordinalSuffix;

        // Classify
        if (rawPercentile < 5) {
          this.childClassify = "Underweight";
        } else if (rawPercentile < 85) {
          this.childClassify = "Normal";
        } else if (rawPercentile < 95) {
          this.childClassify = "Overweight";
        } else {
          this.childClassify = "Obese";
        }
      }
      this.openChildResult = true;
    },
    clearChild() {
      this.$refs.childForm.resetValidation();
      this.childHtUnit = "cm";
      this.childWtUnit = "kg";
      this.childHeight = "";
      this.childInches = "";
      this.childWeight = "";
      this.childSex = 1;
      this.childAge = "";
      this.childBMI = "";
      this.childPercentile = {};
      this.childZScore = "";
      this.childClassify = "";
      this.childBirthday = new Date(
        new Date().setFullYear(new Date().getFullYear() - 2)
      )
        .toISOString()
        .substr(0, 10);
    }
  }
};
</script>

<style scoped>
.height {
  display: grid;
  grid-auto-flow: column;
}
.bday-and-sex {
  display: grid;
  grid-auto-flow: column;
  align-items: center;
  grid-template-columns: 37% 58%;
  justify-content: space-between;
}
</style>

// src/views/Tools/BMICalc.jsx
import {
	Box,
	Card,
	Tabs,
	Tab,
	RadioGroup,
	Radio,
	FormControlLabel,
	TextField,
	InputAdornment,
	Button,
	MenuItem,
	Dialog,
	DialogTitle,
	Table,
	TableBody,
	TableRow,
	TableCell,
	DialogActions,
} from "@mui/material";
import { useState } from "preact/hooks";
import SwipeableViews from "react-swipeable-views";
import BMI_LMS from "../../assets/BMI_LMS.json";
import { useValidation } from "../../functions/customHooks";

function computeBMI(ht, inches, htUnit, wt, wtUnit) {
	let m, kg;

	// Convert height to meters
	m = htUnit === "cm" ? ht * 0.01 : (ht * 12 + +inches) * 0.0254;
	// Convert weight to kg
	kg = wtUnit === "kg" ? wt : wt * 0.45359237;

	// Set BMI
	const bodyMassIndex = (kg / m ** 2).toFixed(1);

	return bodyMassIndex;
}

function classifyBMI(bodyMassIndex) {
	if (bodyMassIndex < 18.5) return { asia: "Underweight", who: "Underweight" };
	if (bodyMassIndex < 23) return { asia: "Normal", who: "Normal" };
	if (bodyMassIndex < 25) return { asia: "Overweight", who: "Normal" };
	if (bodyMassIndex < 30) return { asia: "Obese", who: "Overweight" };
	if (bodyMassIndex < 35) return { asia: "Obese", who: "Obese class I" };
	if (bodyMassIndex < 40) return { asia: "Obese", who: "Obese class II" };

	return { asia: "Obese", who: "Obese class III" };
}

function computeZScore(bodyMassIndex, ageYrs, ageMos, sex) {
	// Convert age to mos
	const ageInMos = Math.round(ageYrs * 12 + +ageMos);
	// Convert sex to number
	const sexNum = sex === "Male" ? 1 : 2;
	const lms = BMI_LMS.find(x => x.sex === sexNum && x.mos === ageInMos);
	const rawZScore = ((bodyMassIndex / lms.m) ** lms.l - 1) / (lms.l * lms.s);

	return rawZScore;
}

function computePercentile(rawZScore) {
	// zscore is the number of standard deviations from the mean

	// If zscore is greater than 6.5 standard deviations from the mean,
	// The number of significant digits will be outside of a reasonable range
	if (rawZScore < -6.5) return 0.0;
	if (rawZScore > 6.5) return 1.0;

	let factK = 1;
	let sum = 0;
	let term = 1;
	let k = 0;
	const loopStop = Math.exp(-23);
	while (Math.abs(term) > loopStop) {
		term =
			(((0.3989422804 * Math.pow(-1, k) * Math.pow(rawZScore, k)) /
				(2 * k + 1) /
				Math.pow(2, k)) *
				Math.pow(rawZScore, k + 1)) /
			factK;
		sum += term;
		k++;
		factK *= k;
	}
	sum += 0.5;

	const rawPercentile = Math.round(sum * 100);

	// Append ordinal suffix
	let ordinalSuffix;
	const placeValue = rawPercentile.toString().split("").reverse();
	if (placeValue[1] !== "1") {
		switch (placeValue[0]) {
			case "1":
				ordinalSuffix = "st";
				break;
			case "2":
				ordinalSuffix = "nd";
				break;
			case "3":
				ordinalSuffix = "rd";
				break;
			default:
				ordinalSuffix = "th";
		}
	} else {
		ordinalSuffix = "th";
	}

	return { rawPercentile, ordinalSuffix };
}

function classifyPercentile(rawPercentile) {
	if (rawPercentile < 5) return { child: "Underweight" };
	if (rawPercentile < 85) return { child: "Normal" };
	if (rawPercentile < 95) return { child: "Overweight" };

	return { child: "Obese" };
}

export default function BMICalc() {
	const [selectedTab, setSelectedTab] = useState(0);

	const [heightUnit, setHeightUnit] = useState("cm");
	const [height, setHeight] = useState("");
	const [inches, setInches] = useState("");
	const [weightUnit, setWeightUnit] = useState("kg");
	const [weight, setWeight] = useState("");
	const [sex, setSex] = useState("Male");
	const [age, setAge] = useState({ years: "", months: "" });
	const [resultsIsOpen, setResultsIsOpen] = useState(false);

	// Results variables
	const [BMI, setBMI] = useState("");
	const [percentile, setPercentile] = useState("");
	const [zScore, setZScore] = useState("");
	const [classification, setClassification] = useState({
		asia: "",
		who: "",
		child: "",
	});

	// Form validations
	const [violations, validation, resetValidation] = useValidation();

	function changeTab(value) {
		clearTab("all");
		setSelectedTab(value);
	}

	function getResults() {
		const forValidation = {
			height: !height || isNaN(height),
			weight: !weight || isNaN(weight),
		};
		if (heightUnit === "ft") {
			forValidation.inches = !inches || isNaN(inches);
		}
		if (selectedTab === 1) {
			const ageInMos = Math.round(age.years * 12 + +age.months);
			forValidation.age = ageInMos < 24 || ageInMos > 240;
		}

		if (!validation(forValidation)) return;

		// Compute BMI
		const bodyMassIndex = computeBMI(
			height,
			inches,
			heightUnit,
			weight,
			weightUnit
		);
		setBMI(bodyMassIndex);

		// Determine if adult or child tab is selected
		if (selectedTab === 0) {
			// Adult

			// Classify BMI
			setClassification(classifyBMI(bodyMassIndex));
		} else {
			// Child

			// Compute ZScore
			const rawZScore = computeZScore(
				bodyMassIndex,
				age.years,
				age.months,
				sex
			);
			setZScore(rawZScore.toFixed(2));

			// Compute Percentile
			const { rawPercentile, ordinalSuffix } = computePercentile(rawZScore);
			setPercentile(rawPercentile + ordinalSuffix);

			// Classify Percentile
			setClassification(classifyPercentile(rawPercentile));
		}
		setResultsIsOpen(true);
	}

	function clearTab(arg) {
		setHeight("");
		setInches("");
		setWeight("");
		setAge({ years: "", months: "" });
		setBMI("");
		setPercentile("");
		setZScore("");
		setClassification({
			asia: "",
			who: "",
			child: "",
		});
		resetValidation();

		if (arg === "all") {
			setHeightUnit("cm");
			setWeightUnit("kg");
			setSex("Male");
		}
	}

	return (
		<>
			<Card variant="outlined">
				<Tabs
					variant="fullWidth"
					value={selectedTab}
					onChange={(_, newValue) => changeTab(newValue)}
				>
					<Tab label="Adult" value={0} />
					<Tab label="Child" value={1} />
				</Tabs>
				<SwipeableViews
					index={selectedTab}
					onChangeIndex={index => changeTab(index)}
				>
					{[...Array(2)].map((_, i) => (
						<Box index={i} sx={styles.tabPanel} key={i}>
							{/* Child Extras */}
							{selectedTab === 1 && (
								<Box sx={styles.childExtrasContainer}>
									{/* Sex */}
									<TextField
										select
										size="small"
										label="Sex"
										value={sex}
										onChange={e => setSex(e.target.value)}
										sx={{ width: "30%" }}
									>
										<MenuItem value="Male">Male</MenuItem>
										<MenuItem value="Female">Female</MenuItem>
									</TextField>
									{/* Age */}
									<Box sx={styles.ageContainer}>
										<TextField
											size="small"
											label="Age"
											type="number"
											value={age.years}
											onChange={e => setAge({ ...age, years: e.target.value })}
											error={violations.age}
											helperText={violations.age && "2-20 y/o"}
											InputProps={{
												endAdornment: (
													<InputAdornment position="end">yrs</InputAdornment>
												),
											}}
											sx={{ width: "50%" }}
										/>
										<TextField
											size="small"
											type="number"
											value={age.months}
											onChange={e => setAge({ ...age, months: e.target.value })}
											error={violations.age}
											InputProps={{
												endAdornment: (
													<InputAdornment position="end">mos</InputAdornment>
												),
											}}
											sx={{ width: "50%" }}
										/>
									</Box>
								</Box>
							)}
							{/* Height */}
							<Box sx={styles.heightContainer}>
								<RadioGroup
									row
									value={heightUnit}
									onChange={e => setHeightUnit(e.target.value)}
								>
									<FormControlLabel
										control={<Radio />}
										value="cm"
										label="Centimeters"
									/>
									<FormControlLabel
										control={<Radio />}
										value="ft"
										label="Feet, inches"
									/>
								</RadioGroup>
								<Box sx={styles.heightFieldContainer}>
									<TextField
										fullWidth
										label="Height"
										type="number"
										size="small"
										autoComplete="off"
										value={height}
										onChange={e => setHeight(e.target.value)}
										error={violations.height}
										InputProps={{
											endAdornment: (
												<InputAdornment position="end">
													{heightUnit}
												</InputAdornment>
											),
										}}
									/>
									{heightUnit === "ft" && (
										<TextField
											fullWidth
											type="number"
											size="small"
											autoComplete="off"
											value={inches}
											onChange={e => setInches(e.target.value)}
											error={violations.inches}
											InputProps={{
												endAdornment: (
													<InputAdornment position="end">in</InputAdornment>
												),
											}}
										/>
									)}
								</Box>
							</Box>

							{/* Weight */}
							<Box sx={styles.weightContainer}>
								<RadioGroup
									row
									value={weightUnit}
									onChange={e => setWeightUnit(e.target.value)}
								>
									<FormControlLabel
										control={<Radio />}
										value="kg"
										label="Kilogram"
									/>
									<FormControlLabel
										control={<Radio />}
										value="lbs"
										label="Pounds"
									/>
								</RadioGroup>
								<TextField
									fullWidth
									label="Weight"
									type="number"
									size="small"
									autoComplete="off"
									value={weight}
									onChange={e => setWeight(e.target.value)}
									error={violations.weight}
									InputProps={{
										endAdornment: (
											<InputAdornment position="end">
												{weightUnit}
											</InputAdornment>
										),
									}}
									sx={styles.weightField}
								/>
							</Box>

							{/* Action Buttons */}
							<Box sx={styles.actionsContainer}>
								<Button onClick={clearTab}>Clear</Button>
								<Button onClick={getResults}>Compute</Button>
							</Box>
						</Box>
					))}
				</SwipeableViews>
			</Card>
			<Dialog
				fullWidth
				maxWidth="xs"
				open={resultsIsOpen}
				PaperProps={{ elevation: 1 }}
			>
				<DialogTitle>Results</DialogTitle>
				<Box sx={styles.resultsContentContainer}>
					<Table size="small" dense>
						<TableBody>
							<TableRow>
								<TableCell>BMI</TableCell>
								<TableCell>{BMI}</TableCell>
							</TableRow>
							{selectedTab === 0 ? (
								<>
									<TableRow>
										<TableCell>Asia Classif.</TableCell>
										<TableCell>{classification.asia}</TableCell>
									</TableRow>
									<TableRow>
										<TableCell>WHO Classif.</TableCell>
										<TableCell>{classification.who}</TableCell>
									</TableRow>
								</>
							) : (
								<>
									<TableRow>
										<TableCell>Percentile</TableCell>
										<TableCell>{percentile}</TableCell>
									</TableRow>
									<TableRow>
										<TableCell>ZScore</TableCell>
										<TableCell>{zScore}</TableCell>
									</TableRow>
									<TableRow>
										<TableCell>Classification</TableCell>
										<TableCell>{classification.child}</TableCell>
									</TableRow>
								</>
							)}
						</TableBody>
					</Table>
				</Box>
				<DialogActions>
					<Button onClick={() => setResultsIsOpen(false)}>Close</Button>
				</DialogActions>
			</Dialog>
		</>
	);
}

const styles = {
	tabPanel: {
		padding: "16px",
	},
	childExtrasContainer: {
		display: "flex",
		justifyContent: "space-between",
		padding: "8px 0 12px",
	},
	weightField: {
		marginTop: "8px",
	},
	ageContainer: {
		width: "65%",
	},
	heightContainer: {
		paddingBottom: "16px",
	},
	heightFieldContainer: {
		display: "flex",
		marginTop: "8px",
	},
	weightContainer: {
		paddingBottom: "16px",
	},
	actionsContainer: {
		display: "flex",
		justifyContent: "flex-end",
		paddingTop: "8px",
	},
	resultsContentContainer: {
		paddingX: "12px",
	},
};
